require 'json'

# Load properties from Podfile.properties.json
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

# Set deployment target
platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4'

# Configure CocoaPods
install! 'cocoapods',
  :deterministic_uuids => false

# Define the main target
target 'Chefing' do
  # Use frameworks for all pods
  use_frameworks! :linkage => :static

  # React Native dependencies
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'

  # Expo dependencies
  pod 'Expo', :path => '../node_modules/expo/'
  pod 'ExpoModulesCore', :path => '../node_modules/expo-modules-core/'
  pod 'ExpoConstants', :path => '../node_modules/expo-constants/'
  pod 'ExpoFileSystem', :path => '../node_modules/expo-file-system/'
  pod 'ExpoFont', :path => '../node_modules/expo-font/'
  pod 'ExpoImage', :path => '../node_modules/expo-image/'
  pod 'ExpoImagePicker', :path => '../node_modules/expo-image-picker/'
  pod 'ExpoLinearGradient', :path => '../node_modules/expo-linear-gradient/'
  pod 'ExpoLinking', :path => '../node_modules/expo-linking/'
  pod 'ExpoMediaLibrary', :path => '../node_modules/expo-media-library/'
  pod 'ExpoNotifications', :path => '../node_modules/expo-notifications/'
  pod 'ExpoRouter', :path => '../node_modules/expo-router/'
  pod 'ExpoSecureStore', :path => '../node_modules/expo-secure-store/'
  pod 'ExpoSplashScreen', :path => '../node_modules/expo-splash-screen/'
  pod 'ExpoStatusBar', :path => '../node_modules/expo-status-bar/'
  pod 'ExpoSystemUI', :path => '../node_modules/expo-system-ui/'
  pod 'ExpoWebBrowser', :path => '../node_modules/expo-web-browser/'

  # Other dependencies
  pod 'Stripe', '~> 23.0'
  pod 'stripe-react-native', :path => '../node_modules/@stripe/stripe-react-native'

  post_install do |installer|
    # Fix for Xcode 14 resource bundles
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Fix for arm64 architecture
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
